### ISSUE TITLE
Contagem de pontos começa com a pontuação anterior.

### ISSUE THREAD

**Issue by gcairesdev** [r3nanp/flappy-bird#10]
Quando o player perde uma partida ele mostra os pontos atingidos, e assim que começa uma nova partida, ao invés de começar com 0 pontos, ele começa com a pontuação da partida anterior.

**Comment by r3nanp** [comment]
Now, I've fixed. :)

[Fix pull request](https://github.com/r3nanp/flappy-bird/pull/11)
